#!/bin/bash

# if ! command -v brew > /dev/null 2>&1; then
#   echo "Installing homebrew"
#   /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#   eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
# fi
#
# if [ -f "$HOME/.Brewfile" ]; then
#   echo "Updating homebrew bundle"
#   brew bundle --global
# fi

if ! command -v curl > /dev/null 2>&1; then
  echo "curl is not found. Please install curl"
  exit 1
fi

if ! command -v git > /dev/null 2>&1; then
  echo "git is not found. Please install git"
  exit 1
fi

if [ ! -e "${HOME}/.history" ]; then
  mkdir -p "${HOME}/.history"
fi

if [ ! -e "${HOME}/.asdf/asdf.sh" ]; then
  git clone https://github.com/asdf-vm/asdf.git "${HOME}"/.asdf --branch v0.14.0
fi

# shellcheck disable=SC1090
. ~/.asdf/asdf.sh

plugins=(
  "ruby"
  "nodejs"
  "direnv"
  "ghq"
  "tmux"
  "neovim"
  "golang"
  "sops"
  "saml2aws"
  "shellcheck"
  "ripgrep"
  "fzf"
  "eza"
  "jq"
  "yq"
  "starship"
  "github-cli"
  "terraform"
  "awscli"
  )


for plugin in "${plugins[@]}" ; do
  asdf plugin add ${plugin}
done

asdf install
