FROM ghcr.io/kompiro/devcontainers/base:latest

LABEL org.opencontainers.image.source=https://github.com/kompiro/yadm
LABEL org.opencontainers.image.description="kompiro development dev environment"
LABEL org.opencontainers.image.licenses=APLv2
