name: Dev Container Build and Push Image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"
jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4.2.2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Extract branch name
        id: extract_branch
        run: echo "BRANCH_NAME=${GITHUB_HEAD_REF##*/}" >> $GITHUB_ENV
        if: ${{ github.event_name == 'pull_request' }}
      - name: Extract ref name
        id: extract_ref
        run: echo "REF_NAME=${{ github.ref }}" | sed 's|.*/||' >> $GITHUB_ENV
        if: ${{ github.event_name == 'push' }}
      - name: Set latest tag for main branch
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "REF_NAME=latest" >> $GITHUB_ENV
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository }}
          cacheFrom: ghcr.io/${{ github.repository }}
          imageTag: ${{ env.BRANCH_NAME || env.REF_NAME }}
          push: always
          noCache: true
